name: wildfire_analysis_env
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.9.5
  - pip:
      - numpy==1.21.2
      - pandas==1.3.2
      - matplotlib==3.4.3
      - seaborn==0.11.2
      - notebook==6.4.3
      - jupyter_nbextensions_configurator==0.4.1
      - scikit-learn==0.24.2